version: "3"
services:
  postgres:
    image: postgres:14-alpine
    networks:
      - concurrent
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: '_postgres'

  mysql:
    image: mysql:8.0
    networks:
      - concurrent
    ports:
      - 3307:3306
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    platform: linux/x86_64

  app:
    build:
      context: app/
    networks:
      - concurrent
    ports:
      - 3000:3000
    depends_on:
      - postgres
    container_name: 'app'

networks:
  concurrent:
    driver: bridge

volumes:
  pg_data:
  mysql_data: