version: "3"
services:
  postgres:
    networks:
      - concurrent
    image: postgres:14-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employee
    volumes:
      - /var/lib/postgresql/data
    container_name: 'c_postgres'

  app:
    build:
      context: app/
    networks:
      - concurrent
    ports:
      - 3000:3000
    depends_on:
      - postgres
    container_name: 'c_app'

networks:
  concurrent:
    driver: bridge
